# secrets.toml
stripe_secret_key = "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"
firebase_api_key = "AIzaSyC7AiuNMtkfrlDpH0n8nUhw17-J5YgWRD8"
